# Generated by Django 2.1.3 on 2018-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_auto_20181222_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=50)),
                ('class_credit', models.CharField(max_length=30)),
                ('class_type', models.CharField(max_length=30)),
                ('class_way', models.CharField(max_length=30)),
                ('class_time', models.CharField(max_length=30)),
                ('class_location', models.CharField(max_length=30)),
                ('class_seat', models.CharField(max_length=30)),
            ],
        ),
    ]
