# Generated by Django 2.1.3 on 2018-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
    ]
